language: android
android:
  components:
    - platform-tools
    - tools

    - build-tools-21.1.2

    - android-21

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

branches:
  only:
    - master
    - develop
